platform :ios, '14.0'

# CocoaPods analytics send network requests periodically.
# Uncomment the following line to disable this.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'src-tauri_iOS' do
  use_frameworks!
  
  # iOS-specific pods for Tauri 2.x
  pod 'Tauri', :path => '../../node_modules/@tauri-apps/cli'
  
  # Network and security
  pod 'TrustKit', '~> 2.0'
  
  # Additional iOS dependencies
  pod 'ReachabilitySwift', '~> 5.0'
  
  target 'src-tauri_iOSTests' do
    inherit! :search_paths
  end
end

# Post-install script for Xcode 15 compatibility and optimization
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # iOS deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # Disable bitcode (not supported in iOS 14+)
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Strip installed product for smaller app size
      config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'
      
      # Optimize for size
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      
      # Warning settings
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      
      # Architecture settings
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['VALIDATE_PRODUCT'] = 'YES'
      
      # Code signing
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      
      # Other optimizations
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['COPY_PHASE_STRIP'] = 'YES'
    end
  end
end