name: Display Cost Warning

description: 'Display cost warning for using GitHub-hosted runners'

inputs:
  cost_warning:
    description: 'Cost warning message'
    required: true
    type: string
  repository:
    description: 'Repository name'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Display Cost Warning
      shell: bash
      run: |
        echo "ðŸ’° Cost Warning Display"
        echo "Repository: ${{ inputs.repository }}"
        echo "Warning: ${{ inputs.cost_warning }}"
        echo ""
        echo "ðŸ’¡ Tip: Consider setting up a self-hosted runner to reduce costs for frequent builds."
        echo ""
        echo "# ðŸ’° Cost Warning" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Repository**: ${{ inputs.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "âš ï¸ ${{ inputs.cost_warning }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "ðŸ’¡ **Tip**: Consider setting up a self-hosted runner to reduce costs for frequent builds." >> $GITHUB_STEP_SUMMARY