name: 'Display Cost Warning'
description: 'Displays a warning when using GitHub-hosted runners instead of self-hosted runners'

inputs:
  cost_warning:
    description: 'The cost warning message to display'
    required: true
  repository:
    description: 'The repository name (owner/repo)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Display Cost Warning Banner
      shell: bash
      run: |
        echo ""
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”“"
        echo "â”ƒ  âš ï¸  COST WARNING: Using GitHub-Hosted Runner               â”ƒ"
        echo "â”£â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”«"
        echo "â”ƒ                                                              â”ƒ"
        echo "â”ƒ  ${{ inputs.cost_warning }}"
        echo "â”ƒ                                                              â”ƒ"
        echo "â”ƒ  ðŸ’¡ To reduce costs, ensure self-hosted runner is online:   â”ƒ"
        echo "â”ƒ     1. SSH to your runner machine                           â”ƒ"
        echo "â”ƒ     2. cd ~/github-runner && ./svc.sh start                 â”ƒ"
        echo "â”ƒ                                                              â”ƒ"
        echo "â”ƒ  ðŸ“Š Check runner status:                                    â”ƒ"
        echo "â”ƒ     https://github.com/${{ inputs.repository }}/settings/actions/runners"
        echo "â”ƒ                                                              â”ƒ"
        echo "â”—â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”›"
        echo ""
        
        # Also add to GitHub Actions annotations
        echo "::warning::${{ inputs.cost_warning }}"

    - name: Add Cost Warning to Summary
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ## âš ï¸ Cost Warning
        
        This build is using a **GitHub-hosted runner** instead of the self-hosted runner.
        
        **Warning:** ${{ inputs.cost_warning }}
        
        ### How to Fix
        1. Check runner status at: https://github.com/${{ inputs.repository }}/settings/actions/runners
        2. If offline, SSH to the runner machine and run:
           ```bash
           cd ~/github-runner && ./svc.sh start
           ```
        3. Re-run this workflow once the runner is online
        
        ---
        EOF
